sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CmkVK8Zt8ropHjza4wyCLNr20j044vf8+u4BP30sHWRbYHVkViIGBjIE2Uzhs8ml8Tj8+BrMIiwgs0elH3I90he3H2UGGaMf2g8b0PcBNGSi4JZvye9QZ51YdSwKf+6bJfKsrvZ4QP4yfjxoE7Ctb9fXe8kJuFE+HsVa4XfNsdP+N3QP0N6AGY7lHj4wrflwpHQTxfMocH5Ka8YXsxaqaRvbpmd05QxFkqoK3Oj1/P0HNybbEXdogi3Y87OF9pFJE5rGjga75A57fsHPApduZ5oYbRwnInuo99IXZ8rSKqRdIw6Tq8G95w9AvB9r8XDjoegu3QGMwlEc3wcMWiGuoqvOfBqzY/UKks4DVccWE8HjOLc6eSzYq8TxSZR5a1w03i5sCAfIBnu1oaQBhV3nPiq9xz2AErjfWj6ZlnprOl29cHnamXWiZ1h4hbSXm5NapQrcH0JA9BXdflTfGSdXtKXKxkE/YAgHZhIvjC+gkgcQwQZNNZLgUpI8Vi8TsLjfyadYcuVRIMfbGsTCwXwcFuYAJ2kGPZHuv4SuhUPAOtEimv2LXbRrU4mOiiHfCFsBTQjH79Kvub30ArkyJY8PlkPuPLBDC+87JswqBPeWVfbTX0iHDH+MG4tK/thYZ8Pfb+qF/mplq/Eh1+C3Sr7qcLg2NfNre726O1v54GmoOOI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Measure-for-Measure_1792
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy